"""Generates the homepage's "Where you'll stay" beat — the drone frame of the
plot, pinned, with the open-air restaurant circled in an opening beat and then
the three houses one at a time in the left margin, each circle drawing itself
where the house stands — and splices it into index.html between its markers.

Run it after editing anything here or in accommodation.html's cards:

    python3 scratchpad/build_plot.py

House names, one-liners, Size/Beds/Sleeps and from-prices are READ FROM
accommodation.html's .cat cards, so the two pages cannot disagree. Only the
photograph per house is chosen here (the cards use smaller frames).

Loop geometry is in viewBox units (1000 x 562 over the 2000 x 1125 frame).
Positions are Frederik's (7–8 Sep 2026): the four leftmost huts (two per row)
are Bali Deluxe, the rest of both rows plus the lone hut to the east are Bali
House, the four in the north-east cluster are Thai Twin, and the restaurant is
the hexagonal roof nearest the water. The styles live in style.css under
"Where you'll stay", the behaviour in script.js as initPlot().
"""
import math, random, re, pathlib, html

ROOT = pathlib.Path(__file__).resolve().parents[1]
A = 'assets/'
START = '<!-- ============ WHERE YOU\'LL STAY (generated by scratchpad/build_plot.py) ============ -->'
END = '<!-- /WHERE YOU\'LL STAY -->'

# --- loop geometry ------------------------------------------------------------
# cx, cy, rx, ry: the box. `n` is the superellipse exponent (2 = ellipse; 6–8 = a
# rounded rectangle, which is what a hand draws round a row of huts). `shear`
# leans the shape: the bottom edge moves right by that much and the top edge
# left, because the back row is offset from the front row. `wob` is the wobble
# amplitude — kept low on the two row loops, where the strokes pass within a
# few units of the neighbouring huts. Step -1 is the opening beat.
LOOPS = {
    'restaurant':  [dict(cx=416, cy=153, rx=38,  ry=33, rot=0.1, n=2.2, shear=0, wob=0.04, seed=15)],
    'bali-house':  [dict(cx=604, cy=479, rx=146, ry=82, rot=0.0, n=8,   shear=16, wob=0.015, seed=11),
                    dict(cx=770, cy=380, rx=36,  ry=26, rot=0.0, n=2,   shear=0,  wob=0.05,  seed=14)],
    'bali-deluxe': [dict(cx=409, cy=479, rx=53.5, ry=82, rot=0.0, n=6,  shear=16, wob=0.015, seed=12)],
    'thai-twin':   [dict(cx=762, cy=290, rx=118, ry=55, rot=0.10, n=2.6, shear=0, wob=0.04,  seed=13)],
}
# hand-lettered names — desktop position, phone position; '|' breaks a line
LABELS = {
    'restaurant':  dict(x=458, y=104, mx=458, my=100, text='Open-air|restaurant'),
    'bali-house':  dict(x=560, y=374, mx=560, my=374, text='Bali House'),
    'bali-deluxe': dict(x=350, y=386, mx=312, my=388, text='Bali Deluxe'),
    'thai-twin':   dict(x=690, y=222, mx=660, my=222, text='Thai Twin House'),
}
# (key, step id, accommodation.html card id)
STEPS = [('restaurant', -1, None), ('bali-house', 0, 'bali-house'), ('bali-deluxe', 1, 'bali-deluxe'), ('thai-twin', 2, 'thai-twin-house')]
# the card frames on accommodation.html are 800x600 at best; these are the sharpest frames of each house
PHOTOS = {
    'bali-house':      (A + 'room-photos/bali-house-sea-view/img_2p9896.webp', 2000, 1500),
    'bali-deluxe':     (A + 'room-photos/bali-deluxe-partial-sea-view/img_9p8136.webp', 2000, 1500),
    'thai-twin-house': (A + 'room-photos/thai-twin-house-garden-view/img_4p680.webp', 750, 500),
}


def loop(cx, cy, rx, ry, rot, n, shear, wob, seed):
    """One marker stroke round a (sheared) superellipse: low-frequency wobble,
    and the pen overshoots its start the way a hand does."""
    random.seed(seed)
    ph = [random.uniform(0, math.tau) for _ in range(3)]
    amp = [random.uniform(wob * 0.6, wob) for _ in range(3)]
    pts, steps = [], 120
    sgn = lambda v: (v > 0) - (v < 0)
    for i in range(steps + 11):
        t = i / steps * math.tau
        w = 1 + sum(a * math.sin(k * t + p) for k, (a, p) in enumerate(zip(amp, ph), start=2))
        c, s_ = math.cos(t), math.sin(t)
        x = rx * w * sgn(c) * abs(c) ** (2 / n)
        y = ry * w * sgn(s_) * abs(s_) ** (2 / n)
        x += shear * (y / ry)                       # lean: bottom right, top left
        xr, yr = x * math.cos(rot) - y * math.sin(rot), x * math.sin(rot) + y * math.cos(rot)
        pts.append((cx + xr, cy + yr))
    return 'M' + ' L'.join(f'{x:.1f} {y:.1f}' for x, y in pts)


def houses():
    """The three cards on accommodation.html, read as data."""
    s = (ROOT / 'accommodation.html').read_text(encoding='utf-8')
    strip = lambda t: html.unescape(re.sub(r'<[^>]+>', '', t)).strip()
    out = {}
    for m in re.finditer(r'<article class="cat" id="([^"]+)">(.*?)</article>', s, re.S):
        cid, body = m.group(1), m.group(2)
        facts = {strip(k): strip(v) for k, v in re.findall(r'<dt>(.*?)</dt>\s*<dd>(.*?)</dd>', body, re.S)}
        price = re.search(r'class="cat__price">\s*from\s+([\d,]+)', body)
        out[cid] = dict(
            id=cid,
            name=strip(re.search(r'class="cat__name">(.*?)</h3>', body, re.S).group(1)),
            line=strip(re.search(r'class="cat__line">(.*?)</p>', body, re.S).group(1)),
            size=facts['Size'], beds=facts['Beds'], sleeps=facts['Sleeps'],
            price=price.group(1),
        )
    return out


def section():
    data = houses()
    svg_paths, labels, cards, tabs = [], [], [], []
    for key, step, cid in STEPS:
        for L in LOOPS[key]:
            svg_paths.append(f'<path class="pen" data-loop="{step}" d="{loop(**L)}"/>')
        Lb = LABELS[key]
        def text(x, y, lh):
            parts = Lb['text'].split('|')
            if len(parts) == 1:
                return parts[0]
            return ''.join(f'<tspan x="{x}" dy="{0 if j == 0 else lh}">{t}</tspan>' for j, t in enumerate(parts))
        labels.append(f'<text class="hand hand--d mark" data-label="{step}" x="{Lb["x"]}" y="{Lb["y"]}">{text(Lb["x"], Lb["y"], 30)}</text>'
                      f'<text class="hand hand--m mark" data-label="{step}" x="{Lb["mx"]}" y="{Lb["my"]}">{text(Lb["mx"], Lb["my"], 36)}</text>')
        if cid is None:
            continue
        h = data[cid]; img, w, hh = PHOTOS[cid]
        cards.append(f'''
        <article class="ph" data-card="{step}">
          <div class="ph__shot"><img src="{img}" alt="{h['name']}" width="{w}" height="{hh}" loading="lazy"></div>
          <h3 class="ph__name">{h['name']}</h3>
          <p class="ph__line">{h['line']}</p>
          <dl class="ph__facts">
            <div><dt>Size</dt><dd>{h['size']}</dd></div>
            <div><dt>Beds</dt><dd>{h['beds']}</dd></div>
            <div><dt>Sleeps</dt><dd>{h['sleeps']}</dd></div>
          </dl>
          <p class="ph__price">from {h['price']} THB <span class="ph__unit">per night</span></p>
          <a class="ph__cta" href="accommodation.html#{cid}">Learn more <span class="arrow" aria-hidden="true">&#8594;</span></a>
        </article>''')
        tabs.append(f'<button type="button" role="tab" class="plot__tab" data-tab="{step}">{h["name"]}</button>')

    return f'''{START}
<section class="plot" data-plot aria-labelledby="plot-h">
  <div class="plot__stage">
    <div class="plot__frame">
      <img class="plot__photo" src="{A}hero-carousel/hero-4.webp" alt="Koh Kood Beach Resort from above: the beach, the pool, the open-air restaurant, the lawn and the bungalows among the palms" width="2000" height="1125" loading="lazy">
      <svg class="plot__svg" viewBox="0 0 1000 562" preserveAspectRatio="xMidYMax slice" data-overlay aria-hidden="true">
        {''.join(svg_paths)}
        {''.join(labels)}
      </svg>
      <div class="plot__scrim"></div>
    </div>
    <div class="plot__side">
      <div class="plot__lead is-on" data-lead>
        <span class="label">The resort from above</span>
        <h2 id="plot-h">Where you'll stay</h2>
        <p>The whole resort in one picture — the beach, the pool, the open-air restaurant, and the houses among the palms. We've circled where each one stands, so you can see for yourself how close to the water you'd be.</p>
        <p class="plot__hint">Scroll to see the houses</p>
      </div>
      <div class="plot__tabs" role="tablist" aria-label="Houses">{''.join(tabs)}</div>
      <div class="plot__deck">{''.join(cards)}
      </div>
    </div>
  </div>
</section>
{END}
'''


def build():
    page = ROOT / 'index.html'
    s = page.read_text(encoding='utf-8')
    block = section()
    if START in s and END in s:
        s = s[:s.index(START)] + block + s[s.index(END) + len(END) + 1:]
    else:
        # first run: the beat replaces the pinned beach photograph AND the sage room slider
        a = s.index('<!-- ============ PINNED PARALLAX IMAGE ============ -->')
        b = s.index('<!-- ============ MARQUEE ============ -->')
        s = s[:a] + block + '\n' + s[b:]
    page.write_text(s, encoding='utf-8')
    print('index.html: beat spliced,', len(block) // 1024, 'KB')


if __name__ == '__main__':
    build()
